version: '2'
services:
    testapp1-app:
        image: testapp1
        external_links:
            - testapp1-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=testApp1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testapp1-mongodb:
        extends:
            file: mongodb.yml
            service: testapp1-mongodb
