version: '2'
services:
    testapp1-mongodb:
        container_name: testapp1-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/testApp1/mongodb/:/data/db/
